spring:
    profiles:
      active:
      - dev
---
server: 
    port: 9006

spring:
   profiles: dev
   application:
    name: platformspringcloud-provider-cancleorder-9006                               # 对外的微服务接口名字 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloudtest?serverTimezone=UTC        # 数据库名称注意?serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.test.projectapi.pojo            # 所有Entity别名类所在包
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone:  http://localhost:9005/eureka
      #defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: platformspringcloud-provider-cancleorder-9006         #好好理解一下这是什么东西？
    prefer-ip-address: true    #访问路径可以显示IP地址

info: 
  app.name: 微服务订购提供接口
  company.name: com.yaxin.project
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
    port: 9006

spring:
   profiles: test
   application:
    name:  platformspringcloud-provider-cancleorder-9006                                  # 对外的微服务接口名字 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloudtest?serverTimezone=UTC        # 数据库名称注意?serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
   
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.test.projectapi.pojo            # 所有Entity别名类所在包
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone:  http://localhost:9005/eureka
      #defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: platformspringcloud-provider-cancleorder-9006    #好好理解一下这是什么东西？
    prefer-ip-address: true    #访问路径可以显示IP地址


