spring:
    profiles:
      active:
      - dev
---
server: 
    port: 9002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.test.springcloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
spring:
   profiles: dev
   application:
    name: platformspringcloud-provider-buyorder-9002                             # 对外的微服务接口名字 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloudtest?serverTimezone=UTC        # 数据库名称注意?serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200         # 等待连接获取的最大超时时间
   redis:
    database: 0
    timeout: 0
    host: 127.0.0.1                                         # Redis服务器地址
    port: 6379                                              # Redis服务器连接端口                                        
    pool:                                                   # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8                                         # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1                                          # 连接池中的最大空闲连接
      max-idle: 8                                           # 连接池中的最小空闲连接
      min-idle: 0

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone:  http://localhost:9005/eureka
      #defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: platformspringcloud-provider-buyorder-9002      #好好理解一下这是什么东西？
    prefer-ip-address: true    #访问路径可以显示IP地址

info: 
  app.name: platformspringcloud   订购微服务提供者
  company.name: com.yaxin.project
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
    port: 9002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.test.springcloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
spring:
   profiles: test
   application:
    name:  platformspringcloud-provider-buyorder-9002                                # 对外的微服务接口名字 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloudtest?serverTimezone=UTC        # 数据库名称注意?serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200          # 等待连接获取的最大超时时间
   redis:
    database: 0
    timeout: 0
    host: 127.0.0.1                                         # Redis服务器地址
    port: 6379                                              # Redis服务器连接端口                                        
    pool:                                                   # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8                                         # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1                                          # 连接池中的最大空闲连接
      max-idle: 8                                           # 连接池中的最小空闲连接
      min-idle: 0

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone:  http://localhost:9005/eureka
      #defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: platformspringcloud-provider-buyorder-9002    #好好理解一下这是什么东西？
    prefer-ip-address: true    #访问路径可以显示IP地址

info: 
  app.name: platformspringcloud 订购微服务提供者
  company.name: com.yaxin.project
  build.artifactId: $project.artifactId$
  build.version: $project.version$
